# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Format
format = '''
$username[@WSL:](bold green)$directory$git_branch$git_status$character'''

right_format  = '''
$cmd_duration$nodejs$all

'''
# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
format = '[$path](bold blue)[$read_only]($read_only_style)'
truncation_length = 5
truncation_symbol = '../'
use_os_path_sep = false

[git_branch]
format = ' on [$symbol$branch(:$remote_branch)](bold fg:214) '
symbol = ' '

[git_status]
style = 'bold fg:214'

[cmd_duration]
min_time = 0
format = '󱦟 [$duration](bold yellow) '

[username]
show_always = true
format = '[$user]($style)'
style_user = 'bold green'

[character]
# success_symbol = "[\uf054](white)" # 
vicmd_symbol = "[\ue62b](white)" # 
error_symbol = "[\uf467](red)" # 
